import {
  Users,
  MessageSquare,
  Calendar,
  Settings,
  Heart,
  Star,
  Target,
  Zap,
  Shield,
  Globe,
  Briefcase,
  BookOpen,
  Music,
  Coffee,
  Camera,
  Gift,
  Flame,
  Sparkles,
  Check,
  Puzzle,
  LayoutDashboard,
  BarChart3,
  Church,
  Cross,
  Book,
  Handshake,
  HeartHandshake,
  Fish,
  Waves,
  Sun,
  Moon,
  Footprints,
  Podcast,
  Video,
  UserCheck,
  Users2,
  GraduationCap,
  Baby,
  TrendingUp,
  Navigation,
  MapPin,
  Home,
  Smile,
  type LucideIcon
} from "lucide-react";

export const iconMap: { [key: string]: LucideIcon } = {
  'Users': Users,
  'MessageSquare': MessageSquare,
  'Calendar': Calendar,
  'Settings': Settings,
  'Heart': Heart,
  'Star': Star,
  'Target': Target,
  'Zap': Zap,
  'Shield': Shield,
  'Globe': Globe,
  'Briefcase': Briefcase,
  'BookOpen': BookOpen,
  'Music': Music,
  'Coffee': Coffee,
  'Camera': Camera,
  'Gift': Gift,
  'Flame': Flame,
  'Sparkles': Sparkles,
  'Check': Check,
  'Puzzle': Puzzle,
  'LayoutDashboard': LayoutDashboard,
  'BarChart3': BarChart3,
  // Faith-related icons
  'Church': Church,
  'Cross': Cross,
  'Book': Book,
  'Handshake': Handshake,
  'HeartHandshake': HeartHandshake,
  'Fish': Fish,
  'Waves': Waves,
  'Sun': Sun,
  'Moon': Moon,
  'Footprints': Footprints,
  // Flow-related icons
  'Podcast': Podcast,
  'Video': Video,
  'UserCheck': UserCheck,
  'Users2': Users2,
  'GraduationCap': GraduationCap,
  'Baby': Baby,
  'TrendingUp': TrendingUp,
  'Navigation': Navigation,
  'MapPin': MapPin,
  'Home': Home,
  'Smile': Smile
};

export const iconOptions = [
  { name: 'Users', icon: Users },
  { name: 'MessageSquare', icon: MessageSquare },
  { name: 'Calendar', icon: Calendar },
  { name: 'Settings', icon: Settings },
  { name: 'Heart', icon: Heart },
  { name: 'Star', icon: Star },
  { name: 'Target', icon: Target },
  { name: 'Zap', icon: Zap },
  { name: 'Shield', icon: Shield },
  { name: 'Globe', icon: Globe },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'Music', icon: Music },
  { name: 'Coffee', icon: Coffee },
  { name: 'Camera', icon: Camera },
  { name: 'Gift', icon: Gift },
  { name: 'Flame', icon: Flame },
  { name: 'Sparkles', icon: Sparkles },
  { name: 'Check', icon: Check },
  { name: 'Puzzle', icon: Puzzle },
  { name: 'LayoutDashboard', icon: LayoutDashboard },
  { name: 'BarChart3', icon: BarChart3 },
  { name: 'Church', icon: Church },
  { name: 'Cross', icon: Cross },
  { name: 'Book', icon: Book },
  { name: 'Handshake', icon: Handshake },
  { name: 'HeartHandshake', icon: HeartHandshake },
  { name: 'Fish', icon: Fish },
  { name: 'Waves', icon: Waves },
  { name: 'Sun', icon: Sun },
  { name: 'Moon', icon: Moon },
  { name: 'Footprints', icon: Footprints },
  { name: 'Podcast', icon: Podcast },
  { name: 'Video', icon: Video },
  { name: 'UserCheck', icon: UserCheck },
  { name: 'Users2', icon: Users2 },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Baby', icon: Baby },
  { name: 'TrendingUp', icon: TrendingUp },
  { name: 'Navigation', icon: Navigation },
  { name: 'MapPin', icon: MapPin },
  { name: 'Home', icon: Home },
  { name: 'Smile', icon: Smile }
];

export const getFlowIcon = (iconName?: string): LucideIcon => {
  if (!iconName) return Users;
  return iconMap[iconName] || Users;
};
