import React, { useCallback, useEffect, useState } from 'react';
import { Building2, Check, AlertTriangle, Loader2, CheckCircle } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';

type SlugStatus = 'idle' | 'checking' | 'available' | 'taken';

interface OrganizationNameCardProps {
  organization: { id: string; name: string; slug: string } | null;
}

/** Heuristic: orgs auto-created at signup are named after the email local part. */
const looksAutoGenerated = (name: string, email?: string | null) => {
  if (!name) return true;
  const local = email?.split('@')[0]?.toLowerCase() ?? '';
  const normalized = name.toLowerCase().replace(/[^a-z0-9]/g, '');
  if (/(church|ministry|organization)$/i.test(name) === false && local && normalized.includes(local.replace(/[^a-z0-9]/g, ''))) {
    return true;
  }
  return /'s (church|organization)$/i.test(name);
};

export const OrganizationNameCard: React.FC<OrganizationNameCardProps> = ({ organization }) => {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [isOwner, setIsOwner] = useState<boolean | null>(null);
  const [name, setName] = useState(organization?.name ?? '');
  const [slugStatus, setSlugStatus] = useState<SlugStatus>('idle');
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [currentSlug, setCurrentSlug] = useState('');
  const [saving, setSaving] = useState(false);
  const [userEmail, setUserEmail] = useState<string | null>(null);

  useEffect(() => {
    setName(organization?.name ?? '');
  }, [organization?.name]);

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => setUserEmail(data.user?.email ?? null));
  }, []);

  useEffect(() => {
    let cancelled = false;
    const orgId = organization?.id;
    if (!orgId) {
      setIsOwner(null);
      return;
    }
    (async () => {
      const { data: userData } = await supabase.auth.getUser();
      const uid = userData.user?.id;
      if (!uid) {
        if (!cancelled) setIsOwner(false);
        return;
      }
      const { data } = await supabase
        .from('organization_members')
        .select('role')
        .eq('organization_id', orgId)
        .eq('user_id', uid)
        .maybeSingle();
      if (!cancelled) setIsOwner(data?.role === 'owner');
    })();
    return () => {
      cancelled = true;
    };
  }, [organization?.id]);

  const checkSlug = useCallback(
    async (value: string) => {
      const trimmed = value.trim();
      if (!trimmed || trimmed.length < 2 || trimmed === organization?.name) {
        setSlugStatus('idle');
        setSuggestions([]);
        setCurrentSlug('');
        return;
      }
      setSlugStatus('checking');
      try {
        const { data, error } = await supabase.functions.invoke('check-org-slug', {
          body: { organizationName: trimmed },
        });
        if (error) {
          setSlugStatus('idle');
          return;
        }
        setCurrentSlug(data.slug);
        if (data.available) {
          setSlugStatus('available');
          setSuggestions([]);
        } else {
          setSlugStatus('taken');
          setSuggestions(data.suggestions || []);
        }
      } catch {
        setSlugStatus('idle');
      }
    },
    [organization?.name],
  );

  useEffect(() => {
    const t = setTimeout(() => checkSlug(name), 500);
    return () => clearTimeout(t);
  }, [name, checkSlug]);

  const handleSuggestionClick = (suggestion: string) => {
    setName(
      suggestion
        .split('-')
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' '),
    );
  };

  const handleSave = async () => {
    if (!organization) return;
    const trimmed = name.trim();
    if (!trimmed || trimmed === organization.name) return;
    setSaving(true);
    try {
      const { error } = await supabase
        .from('organizations')
        .update({ name: trimmed, ...(currentSlug ? { slug: currentSlug } : {}) })
        .eq('id', organization.id);
      if (error) throw error;
      await queryClient.invalidateQueries({ queryKey: ['profile-organization'] });
      toast({
        title: 'Church name updated',
        description: `Your organization is now "${trimmed}".`,
      });
      setSlugStatus('idle');
    } catch (err: any) {
      toast({
        title: 'Update failed',
        description: err?.message ?? 'Could not update your church name.',
        variant: 'destructive',
      });
    } finally {
      setSaving(false);
    }
  };

  const needsNaming = looksAutoGenerated(organization?.name ?? '', userEmail);
  const disabled = saving || slugStatus === 'taken' || slugStatus === 'checking' || !name.trim() || name.trim() === organization?.name;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-lg bg-emerald-100 flex items-center justify-center">
            <Building2 className="h-5 w-5 text-sidebar-foreground" />
          </div>
          <div>
            <CardTitle className="font-light">Your Church</CardTitle>
            <CardDescription>Name your church or organization and pick its public address</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {needsNaming && (
          <Alert>
            <AlertDescription>
              We created a placeholder name for your organization. Set your real church name so public pages and
              forms look right.
            </AlertDescription>
          </Alert>
        )}

        <div className="space-y-2">
          <Label htmlFor="org-name">Church / Organization Name</Label>
          <Input
            id="org-name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Grace Community Church"
          />

          {slugStatus === 'checking' && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-3 w-3 animate-spin" />
              <span>Checking availability...</span>
            </div>
          )}

          {slugStatus === 'available' && (
            <div className="flex items-center gap-2 text-sm text-green-600">
              <Check className="h-3 w-3" />
              <span>"{currentSlug}" is available!</span>
            </div>
          )}

          {slugStatus === 'taken' && (
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-sm text-destructive">
                <AlertTriangle className="h-3 w-3" />
                <span>This name is taken. Try one of these:</span>
              </div>
              <div className="flex flex-wrap gap-2">
                {suggestions.map((s) => (
                  <Badge
                    key={s}
                    variant="outline"
                    className="cursor-pointer hover:bg-primary hover:text-primary-foreground transition-colors"
                    onClick={() => handleSuggestionClick(s)}
                  >
                    {s}
                  </Badge>
                ))}
              </div>
            </div>
          )}

          {organization?.slug && (
            <p className="text-xs text-muted-foreground">Current public address: /{organization.slug}</p>
          )}
        </div>

        <div className="flex justify-end">
          <Button onClick={handleSave} disabled={disabled} className="w-full sm:w-auto">
            <CheckCircle className="h-4 w-4 mr-2" />
            {saving ? 'Saving...' : 'Save Church Name'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};
