// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lghamvpolwebtjwaxned.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnaGFtdnBvbHdlYnRqd2F4bmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjE0OTEsImV4cCI6MjA3MTQ5NzQ5MX0.yrtGMayjKCu0-K41XWanNe7U3zM0z39cK1fy1OgN7E4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage that respects the "Remember me" preference.
// - Remember me ON  → localStorage (persists across browser restarts)
// - Remember me OFF → sessionStorage (cleared when the tab/window closes)
// The preference flag itself always lives in localStorage so we know which
// store to read from on initial page load.
const REMEMBER_ME_KEY = 'sb-remember-me';

export const setRememberMe = (remember: boolean) => {
  try {
    localStorage.setItem(REMEMBER_ME_KEY, remember ? 'true' : 'false');
  } catch {
    // ignore storage errors (private mode, etc.)
  }
};

export const getRememberMe = (): boolean => {
  try {
    // Default to true so existing users keep their long-lived sessions
    const v = localStorage.getItem(REMEMBER_ME_KEY);
    return v === null ? true : v === 'true';
  } catch {
    return true;
  }
};

const hybridStorage = {
  getItem: (key: string): string | null => {
    try {
      // Read from whichever store currently has the key.
      // sessionStorage takes precedence so an in-tab session wins over a stale localStorage value.
      return sessionStorage.getItem(key) ?? localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      if (getRememberMe()) {
        localStorage.setItem(key, value);
        sessionStorage.removeItem(key);
      } else {
        sessionStorage.setItem(key, value);
        localStorage.removeItem(key);
      }
    } catch {
      // ignore
    }
  },
  removeItem: (key: string): void => {
    try {
      localStorage.removeItem(key);
      sessionStorage.removeItem(key);
    } catch {
      // ignore
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: hybridStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
