// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage that respects the "Remember me" preference.
// - Remember me ON  → localStorage (persists across browser restarts)
// - Remember me OFF → sessionStorage (cleared when the tab/window closes)
// The preference flag itself always lives in localStorage so we know which
// store to read from on initial page load.
const REMEMBER_ME_KEY = 'sb-remember-me';

const getStoredSessionExpiry = (value: string | null): number => {
  if (!value) return 0;

  try {
    const parsed = JSON.parse(value);
    return typeof parsed?.expires_at === 'number' ? parsed.expires_at : 0;
  } catch {
    return 0;
  }
};

export const setRememberMe = (remember: boolean) => {
  try {
    localStorage.setItem(REMEMBER_ME_KEY, remember ? 'true' : 'false');
  } catch {
    // ignore storage errors (private mode, etc.)
  }
};

export const getRememberMe = (): boolean => {
  try {
    // Default to true so existing users keep their long-lived sessions
    const v = localStorage.getItem(REMEMBER_ME_KEY);
    return v === null ? true : v === 'true';
  } catch {
    return true;
  }
};

const hybridStorage = {
  getItem: (key: string): string | null => {
    try {
      // Read from whichever store currently has the newest session.
      // This prevents an old tab-scoped session from shadowing a newer remembered login.
      const sessionValue = sessionStorage.getItem(key);
      const localValue = localStorage.getItem(key);

      if (!sessionValue || !localValue) return sessionValue ?? localValue;

      return getStoredSessionExpiry(sessionValue) >= getStoredSessionExpiry(localValue)
        ? sessionValue
        : localValue;
    } catch {
      return null;
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      if (getRememberMe()) {
        localStorage.setItem(key, value);
        sessionStorage.removeItem(key);
      } else {
        sessionStorage.setItem(key, value);
        localStorage.removeItem(key);
      }
    } catch {
      // ignore
    }
  },
  removeItem: (key: string): void => {
    try {
      localStorage.removeItem(key);
      sessionStorage.removeItem(key);
    } catch {
      // ignore
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: hybridStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
